FROM public.ecr.aws/docker/library/alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
ARG BINARY
COPY --chown=65534:65534 ${BINARY} /service
RUN chmod 755 /service
USER 65534:65534
ENTRYPOINT ["/service"]
