# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
kotlin.incremental=false
kotlin.daemon.useFallbackStrategy=true
